name: Build and Test
on: [push]
jobs:
  webApp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-dotnet@v1
      #  with: { dotnet-version: 5.0.x }
      - run: dotnet restore Eventures.App.UnitTests
      - run: dotnet build Eventures.App.UnitTests --no-restore
      - run: dotnet test Eventures.App.UnitTests --no-build --verbosity normal
      - run: dotnet restore Eventures.App.IntegrationTests
      - run: dotnet build Eventures.App.IntegrationTests --no-restore
      - run: dotnet test Eventures.App.IntegrationTests --no-build --verbosity normal
      - run: dotnet restore Eventures.App.SeleniumTests
      - run: dotnet build Eventures.App.SeleniumTests --no-restore
      - run: dotnet test Eventures.App.SeleniumTests --no-build --verbosity normal
  webApi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: { dotnet-version: 5.0.x }
      - run: dotnet restore Eventures.WebAPI.UnitTests 
      - run: dotnet build Eventures.WebAPI.UnitTests --no-restore
      - run: dotnet test Eventures.WebAPI.UnitTests --no-build --verbosity normal
      - run: dotnet restore Eventures.WebAPI.IntegrationTests
      - run: dotnet build Eventures.WebAPI.IntegrationTests --no-restore
      - run: dotnet test Eventures.WebAPI.IntegrationTests --no-build --verbosity normal
  desktopApp-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: { dotnet-version: 5.0.x }
      # Install Node.js, install Appium, run Appium on ::1: and run the Appium tests
      - uses: actions/setup-node@v2
        with: { node-version: '14' }
      - run: dotnet restore Eventures.Desktop
      - run: dotnet build Eventures.Desktop --no-restore
      - run: dotnet restore Eventures.Desktop.AppiumTests
      - run: dotnet build Eventures.Desktop.AppiumTests --no-restore
      - run: npm install -g appium
      - run: dotnet test Eventures.Desktop.AppiumTests --no-build --verbosity normal
