name: Build and Test
on: [push]
jobs:
  WebApp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore Eventures.WebApp.UnitTests
      - run: dotnet build Eventures.WebApp.UnitTests --no-restore
      - run: dotnet test Eventures.WebApp.UnitTests --no-build --verbosity normal
      - run: dotnet restore Eventures.WebApp.IntegrationTests
      - run: dotnet build Eventures.WebApp.IntegrationTests --no-restore
      - run: dotnet test Eventures.WebApp.IntegrationTests --no-build --verbosity normal
      - run: dotnet restore Eventures.WebApp.SeleniumTests
      - run: dotnet build Eventures.WebApp.SeleniumTests --no-restore
      - run: dotnet test Eventures.WebApp.SeleniumTests --no-build --verbosity normal
  WebApi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore Eventures.WebAPI.UnitTests 
      - run: dotnet build Eventures.WebAPI.UnitTests --no-restore
      - run: dotnet test Eventures.WebAPI.UnitTests --no-build --verbosity normal
      - run: dotnet restore Eventures.WebAPI.IntegrationTests
      - run: dotnet build Eventures.WebAPI.IntegrationTests --no-restore
      - run: dotnet test Eventures.WebAPI.IntegrationTests --no-build --verbosity normal
  DesktopApp-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore Eventures.Desktop
      - run: dotnet build Eventures.Desktop --no-restore
      - run: dotnet restore Eventures.Desktop.AppiumTests
      - run: dotnet build Eventures.Desktop.AppiumTests --no-restore
      - run: npm install -g appium
      - run: dotnet test Eventures.Desktop.AppiumTests --no-build --verbosity normal
  AndroidApp-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew.bat assembleRelease
      - run: dotnet restore Eventures.AndroidApp.AppiumTests
      - run: dotnet build Eventures.AndroidApp.AppiumTests --no-restore
      - run: npm install -g appium
      - run: dotnet test Eventures.AndroidApp.AppiumTests --no-build --verbosity normal
